// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storage.proto

#include "storage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace proto {
class StorageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Storage>
      _instance;
} _Storage_default_instance_;
}  // namespace proto
namespace protobuf_storage_2eproto {
static void InitDefaultsStorage() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::proto::_Storage_default_instance_;
    new (ptr) ::proto::Storage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::proto::Storage::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Storage =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsStorage}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Storage.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::Storage, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::Storage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::Storage, current_term_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::Storage, voted_for_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::proto::Storage, log_),
  0,
  1,
  ~0u,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, sizeof(::proto::Storage)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::proto::_Storage_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "storage.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\rstorage.proto\022\005proto\"\?\n\007Storage\022\024\n\014cur"
      "rent_term\030\001 \002(\005\022\021\n\tvoted_for\030\002 \002(\005\022\013\n\003lo"
      "g\030\003 \003(\t"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 87);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "storage.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_storage_2eproto
namespace proto {

// ===================================================================

void Storage::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Storage::kCurrentTermFieldNumber;
const int Storage::kVotedForFieldNumber;
const int Storage::kLogFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Storage::Storage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_storage_2eproto::scc_info_Storage.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:proto.Storage)
}
Storage::Storage(const Storage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      log_(from.log_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&current_term_, &from.current_term_,
    static_cast<size_t>(reinterpret_cast<char*>(&voted_for_) -
    reinterpret_cast<char*>(&current_term_)) + sizeof(voted_for_));
  // @@protoc_insertion_point(copy_constructor:proto.Storage)
}

void Storage::SharedCtor() {
  ::memset(&current_term_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&voted_for_) -
      reinterpret_cast<char*>(&current_term_)) + sizeof(voted_for_));
}

Storage::~Storage() {
  // @@protoc_insertion_point(destructor:proto.Storage)
  SharedDtor();
}

void Storage::SharedDtor() {
}

void Storage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Storage::descriptor() {
  ::protobuf_storage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_storage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Storage& Storage::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_storage_2eproto::scc_info_Storage.base);
  return *internal_default_instance();
}


void Storage::Clear() {
// @@protoc_insertion_point(message_clear_start:proto.Storage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  log_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    ::memset(&current_term_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&voted_for_) -
        reinterpret_cast<char*>(&current_term_)) + sizeof(voted_for_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Storage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:proto.Storage)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 current_term = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_current_term();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &current_term_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // required int32 voted_for = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          set_has_voted_for();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &voted_for_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string log = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_log()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->log(this->log_size() - 1).data(),
            static_cast<int>(this->log(this->log_size() - 1).length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "proto.Storage.log");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:proto.Storage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:proto.Storage)
  return false;
#undef DO_
}

void Storage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:proto.Storage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 current_term = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->current_term(), output);
  }

  // required int32 voted_for = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->voted_for(), output);
  }

  // repeated string log = 3;
  for (int i = 0, n = this->log_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->log(i).data(), static_cast<int>(this->log(i).length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "proto.Storage.log");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->log(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:proto.Storage)
}

::google::protobuf::uint8* Storage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:proto.Storage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 current_term = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->current_term(), target);
  }

  // required int32 voted_for = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->voted_for(), target);
  }

  // repeated string log = 3;
  for (int i = 0, n = this->log_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->log(i).data(), static_cast<int>(this->log(i).length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "proto.Storage.log");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(3, this->log(i), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:proto.Storage)
  return target;
}

size_t Storage::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:proto.Storage)
  size_t total_size = 0;

  if (has_current_term()) {
    // required int32 current_term = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->current_term());
  }

  if (has_voted_for()) {
    // required int32 voted_for = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->voted_for());
  }

  return total_size;
}
size_t Storage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:proto.Storage)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required int32 current_term = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->current_term());

    // required int32 voted_for = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->voted_for());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // repeated string log = 3;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->log_size());
  for (int i = 0, n = this->log_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->log(i));
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Storage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:proto.Storage)
  GOOGLE_DCHECK_NE(&from, this);
  const Storage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Storage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:proto.Storage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:proto.Storage)
    MergeFrom(*source);
  }
}

void Storage::MergeFrom(const Storage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:proto.Storage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  log_.MergeFrom(from.log_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      current_term_ = from.current_term_;
    }
    if (cached_has_bits & 0x00000002u) {
      voted_for_ = from.voted_for_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void Storage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:proto.Storage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Storage::CopyFrom(const Storage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:proto.Storage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Storage::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;
  return true;
}

void Storage::Swap(Storage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Storage::InternalSwap(Storage* other) {
  using std::swap;
  log_.InternalSwap(CastToBase(&other->log_));
  swap(current_term_, other->current_term_);
  swap(voted_for_, other->voted_for_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Storage::GetMetadata() const {
  protobuf_storage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_storage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::proto::Storage* Arena::CreateMaybeMessage< ::proto::Storage >(Arena* arena) {
  return Arena::CreateInternal< ::proto::Storage >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
